settings:
  title: 'Status Page'
  url: 'https://status.jscdn.cn' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: link-gimhoy # unique identifier
    name: link.gimhoy.com
    description: '' # default=empty
    url: 'https://link.gimhoy.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: onedrive-gimhoy # unique identifier
    name: onedrive.gimhoy.com
    description: '' # default=empty
    url: 'https://onedrive.gimhoy.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: link-jscdn # unique identifier
    name: link.jscdn.cn
    description: '' # default=empty
    url: 'https://link.jscdn.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: cf-slb-jscdn # unique identifier
    name: cf-slb.jscdn.cn
    description: '' # default=empty
    url: 'https://cf-slb.jscdn.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: sp-slb-jscdn # unique identifier
    name: sp-slb.jscdn.cn
    description: '' # default=empty
    url: 'https://sp-slb.jscdn.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
